spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trades
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  ai:
    mcp:
      server:
        type: SYNC
        stdio: true
        name: trade-mcp-server
        version: 1.0.0
  main:
    web-application-type: none
    banner-mode: off
  output:
    ansi:
      enabled: never
logging:
  pattern:
    console:
#  level:
#    root: debug